a.out:client.c
	gcc client.c ../common/chat_ui.c ../common/common.c ../common/data.c ../common/udp_client.c ../common/send_chat.c ../common1/udp_create.c -I ../common/ -I ../common1/ -D _D -lpthread -lncursesw
